# This file was generated by GoReleaser. DO NOT EDIT.
cask "lu-hut" do
  name "lu-hut"
  desc "A powerful modern alternative to the Unix ls command"
  homepage "https://github.com/ipanardian/lu-hut"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lu"

  on_macos do
    on_intel do
      url "https://github.com/ipanardian/lu-hut/releases/download/v#{version}/lu-hut_#{version}_Darwin_x86_64.tar.gz"
      sha256 "07b326318a1a5fa411582ef8c34a78903055849f60034065028d647d739fd686"
    end
    on_arm do
      url "https://github.com/ipanardian/lu-hut/releases/download/v#{version}/lu-hut_#{version}_Darwin_arm64.tar.gz"
      sha256 "0cfb49b909495584cb9eb6c4125273e4d0948bb0ce44499408f0edcdba9274c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ipanardian/lu-hut/releases/download/v#{version}/lu-hut_#{version}_Linux_x86_64.tar.gz"
      sha256 "6062b82cc0645df893a166c7aa93cae4edd61a0965f243b3c600b0c0f246b942"
    end
    on_arm do
      url "https://github.com/ipanardian/lu-hut/releases/download/v#{version}/lu-hut_#{version}_Linux_arm64.tar.gz"
      sha256 "17b5e18d2969fd5a31f7eb5da7acf198d6d6de43c158d57b072e2b1dbf9695df"
    end
  end

  # No zap stanza required
end
