# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LuHut < Formula
  desc "A powerful modern alternative to the Unix ls command"
  homepage "https://github.com/ipanardian/lu-hut"
  version "0.6.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ipanardian/lu-hut/releases/download/v0.6.0/lu-hut_0.6.0_Darwin_x86_64.tar.gz"
      sha256 "90a2b01e5fdf00d24474d5325ee182d2eb343d00e51b7b68e41613ec0458c058"

      define_method(:install) do
        bin.install "lu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ipanardian/lu-hut/releases/download/v0.6.0/lu-hut_0.6.0_Darwin_arm64.tar.gz"
      sha256 "b7678aca1adaeec3983c83a75fcb5123fc0326d10cd597620916dea21747f496"

      define_method(:install) do
        bin.install "lu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipanardian/lu-hut/releases/download/v0.6.0/lu-hut_0.6.0_Linux_x86_64.tar.gz"
      sha256 "c2d4a352e93696d0a949892cca4871506f5f7e96701fe85d71fac59ef9e8af69"
      define_method(:install) do
        bin.install "lu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipanardian/lu-hut/releases/download/v0.6.0/lu-hut_0.6.0_Linux_arm64.tar.gz"
      sha256 "ce634d1af5fa5eb616375338b074cf17915d456d1c38a7b46e55832a11031eb5"
      define_method(:install) do
        bin.install "lu"
      end
    end
  end

  test do
    system "#{bin}/lu", "version"
  end
end
