# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LuHut < Formula
  desc "A powerful modern alternative to the Unix ls command"
  homepage "https://github.com/ipanardian/lu-hut"
  version "0.5.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ipanardian/lu-hut/releases/download/v0.5.1/lu-hut_0.5.1_Darwin_x86_64.tar.gz"
      sha256 "a94d8a97ebda1bb3cf8f061b67f0647f824dbbdd9b94b3866f4304fdeb16a5d5"

      def install
        bin.install "lu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ipanardian/lu-hut/releases/download/v0.5.1/lu-hut_0.5.1_Darwin_arm64.tar.gz"
      sha256 "644f2226cec3be8cdc2c14f60c31c6f4c444b108b22b6bb5a0a4b08723978884"

      def install
        bin.install "lu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipanardian/lu-hut/releases/download/v0.5.1/lu-hut_0.5.1_Linux_x86_64.tar.gz"
      sha256 "d1fc96c4fd79c261665cddaced74cb82605ea499d613659dfad51aeab56289c3"
      def install
        bin.install "lu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipanardian/lu-hut/releases/download/v0.5.1/lu-hut_0.5.1_Linux_arm64.tar.gz"
      sha256 "25c12b3a9d3dc3b136e1e33511d1266f4e5efa941122b88f537ba36c2a55f99e"
      def install
        bin.install "lu"
      end
    end
  end

  test do
    system "#{bin}/lu", "version"
  end
end
